### ISSUE TITLE
any way to play this?

### ISSUE THREAD

**Issue by sanidhya711** [Isebyte/74-Cypress-Street#1]
your old visual novel also gets stuck at the same point ever time on my system idk why

**Comment by Isebyte** [comment]
Hi @sanidhya711 , my older VN's development has been put on hold indefinitely, and was more of a test/learning project for me as I was trying to build the engine from scratch. However this current VN is under development using a preexisting framework and is only at the very beginning stages of development. I do plan to continue working on this sometime in the future.

Thanks for checking my repos out though lol
